### ISSUE TITLE
Show command output in the console

### ISSUE THREAD

**Issue by fczbkk** [rpl/grunt-mozilla-addon-sdk#12]
I have created a task that runs `cfx test` command every time I make some change in my code. It's configuration looks like this:

```
'mozilla-cfx':
  test_stable:
    options:
      'mozilla-addon-sdk': '1_15'
      extension_dir: 'extension/firefox'
      command: 'test'
```

The task works, the command is executed. The problem is, that it does not output anything in the console:

```
Running "mozilla-cfx:test_stable" (mozilla-cfx) task
Done, without errors.
```

There's no way I can see if the tests passed or failed. So the task, even if it runs correctly, is not usable for running the test command. I would like it to show the command output in the console. Which, when running the `cfx test` command, should look like this:

```
..
2 of 2 tests passed.
Total time: 1.877000 seconds
Program terminated successfully.
```
